# 데이터 설정
data:
  dataset_name: "LAIR"  # 데이터셋 이름
  selected_primitives_ids: "0"  # 사용할 프리미티브 ID
  workspace_dimensions: 2  # 작업 공간 차원
  dynamical_system_order: 2  # 동역학계 차수
  trajectories_resample_length: 50  # 궤적 리샘플링 길이
  workspace_boundaries_type: "from data"  # 작업 공간 경계 유형
  spline_sample_type: "from data resample"  # 스플라인 샘플링 유형
  evaluation_samples_length: 10  # 평가 샘플 길이
  imitation_window_size: 2  # 모방 윈도우 크기
  
  batch_size: 250  # 배치 크기
  use_cached_data: false  # 캐시된 데이터 사용 여부
  data_dir: "results/data"  # 데이터 저장 디렉토리
  shuffle: true  # 셔플 여부
  num_workers: 4  # 데이터 로더 워커 수
  pin_memory: true  # 메모리 고정 여부

# 모델 설정
model:
  latent_dim: 4  # 잠재 공간 차원
  multi_motion: false  # 다중 동작 원시 지원 여부
  encoder_hidden_sizes: [300, 300]  # 인코더 은닉층 크기
  decoder_hidden_sizes: [300, 300]  # 디코더 은닉층 크기


# 학습 설정
training:
  epochs: 1  # 전체 학습 에포크 수
  epochs_autoencoder: 1  # 오토인코더 학습 에포크
  learning_rates:
    encoder: 1.0e-4  # 인코더 학습률
    decoder: 1.0e-4  # 디코더 학습률
  weight_decay: 1.0e-5  # 가중치 감쇠

# 경로 설정
paths:
  save_dir: "results/model_with_viz"  # 저장 디렉토리
  encoder_path: results/ver8/encoder_triplet_ver8.pt  # 인코더 체크포인트 경로 (null이면 새로 학습)

# 시각화 설정
visualization:
  enable: true  # 시각화 활성화 여부
  max_samples: 6  # 최대 샘플 수
  n_samples_per_primitive: 3  # 프리미티브당 샘플 수
  steps: 50  # 생성 스텝 수
  
  # 데이터셋 기반 시각화 설정
  dataset_visualization:
    enable: true  # 데이터셋 기반 시각화 활성화 여부
    primitive_ids: [0] # 시각화할 프리미티브 ID 목록
    trajectory_ids: [0]  # 시각화할 궤적 ID 목록 (각 프리미티브 내에서)
    n_samples: 5  # 각 궤적당 샘플링할 포인트 수
    sampling_radius: 0.1  # 시작점 주변 샘플링 반경
    steps: 50  # 생성할 궤적의 스텝 수

# # 일괄 궤적 평가 설정
# batch_evaluation:
#   enable: true  # 일괄 평가 활성화 여부
#   primitive_ids: null  # 평가할 프리미티브 ID 목록 (null이면 모든 프리미티브)
#   trajectories_per_primitive: 3  # 각 프리미티브당 평가할 궤적 수
#   n_samples: 5  # 각 궤적당 샘플링할 포인트 수
#   steps: 100  # 생성할 궤적의 스텝 수
#   sample_radius: 0.1  # 시작점 주변 샘플링 반경
#   seed: 42  # 난수 생성 시드 (재현 가능성을 위해)
